dist: jammy
language: python
python:
   - "3.8"
   - "3.9"
   - "3.10"
   - "3.11"

env:
   - PIPENV_IGNORE_VIRTUALENVS=1

install:
   - pip install pipenv
   - pipenv install --dev
   
   
script:
   - pipenv run python -u test/test.py --schema_source=https://www.dmtf.org/sites/default/files/standards/documents/DSP8010_2020.2.zip
   - pipenv run behave -D schema_sources="[{'source':'http', 'url':'https://www.dmtf.org/sites/default/files/standards/documents/DSP8010_2020.2.zip', 'schema_dir':'tmp_schema', 'csdl_dir':'csdl', 'json_schema_dir':'json-schema'}]" test/features
   - test/test_cli.sh
