language: python
python:
   - "3.6"
   - "3.6-dev"
   - "3.7-dev"
   
install:
   - pip install pipenv
   - pipenv install
   
   
script:
   - pipenv run python -u test/test.py 
   - test/test_cli.sh
