language: python
python:
   - "3.6"
   - "3.6-dev"
   - "3.7-dev"

env:
   - PIPENV_IGNORE_VIRTUALENVS=1

install:
   - pip install pipenv
   - pipenv install --dev
   
   
script:
   - pipenv run python -u test/test.py
   - pipenv run behave -D schema_source=https://github.com/DMTF/Redfish.git -D branch=2018.3 -D schema_dir=tmp_schema -D dictionary_dir=tmp_dict features
   - test/test_cli.sh
